"use server";
import { z } from "zod";
import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { notifyCareAssignment, notifyPublishedPrayer } from "@/lib/care/notify";

async function requireCareWorker() {
  const supabase=await createClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) throw new Error("No autenticado");
  const [{data:member},{data:roles}]=await Promise.all([supabase.from("care_team_members").select("active,can_assign,is_supervisor,can_triage,lead_prayer,can_prayer_followup").eq("user_id",user.id).maybeSingle(),supabase.from("user_roles").select("role").eq("user_id",user.id)]);
  const isAdmin=(roles??[]).some((r)=>r.role==="admin"||r.role==="superadmin"); if(!isAdmin&&!member?.active) throw new Error("Sin acceso al equipo de cuidado");
  return {supabase,user,member,isAdmin};
}
function refresh(){revalidatePath("/cuidado");revalidatePath("/admin/cuidado");revalidatePath("/oracion");revalidatePath("/oracion/mis-solicitudes");revalidatePath("/notificaciones");}

export async function updateAssignedCareStatus(formData:FormData){const requestId=z.string().uuid().parse(formData.get("requestId"));const status=z.enum(["contacted","scheduled","completed"]).parse(formData.get("status"));const {supabase}=await requireCareWorker();const {error}=await supabase.from("care_requests").update({status,completed_at:status==="completed"?new Date().toISOString():null}).eq("id",requestId);if(error)throw new Error("No tienes permiso para actualizar este caso o ocurrió un error.");refresh();}
export async function addAssignedCareNote(formData:FormData){const requestId=z.string().uuid().parse(formData.get("requestId"));const note=z.string().trim().min(2).max(3000).parse(formData.get("note"));const {supabase,user}=await requireCareWorker();const {error}=await supabase.from("care_request_notes").insert({request_id:requestId,author_id:user.id,note});if(error)throw new Error("No tienes permiso para agregar una nota a este caso.");refresh();}
export async function assignCareRequestAsLeader(formData:FormData){const requestId=z.string().uuid().parse(formData.get("requestId"));const userId=z.string().uuid().parse(formData.get("userId"));const {supabase,user}=await requireCareWorker();const {data:req,error:readError}=await supabase.from("care_requests").select("request_type").eq("id",requestId).single();if(readError||!req)throw new Error("Caso no disponible.");const {error}=await supabase.from("care_assignments").upsert({request_id:requestId,user_id:userId,assigned_by:user.id});if(error)throw new Error("No tienes permiso para asignar este caso.");await supabase.from("care_requests").update({status:"assigned"}).eq("id",requestId);await notifyCareAssignment(userId,requestId,req.request_type);refresh();}
export async function unassignCareRequestAsLeader(formData:FormData){const requestId=z.string().uuid().parse(formData.get("requestId"));const userId=z.string().uuid().parse(formData.get("userId"));const {supabase}=await requireCareWorker();const {error}=await supabase.from("care_assignments").delete().eq("request_id",requestId).eq("user_id",userId);if(error)throw new Error("No tienes permiso para quitar esta asignación.");refresh();}
export async function moderateCarePrayer(formData:FormData){const prayerId=z.string().uuid().parse(formData.get("prayerId"));const status=z.enum(["approved","rejected","answered"]).parse(formData.get("status"));const {supabase}=await requireCareWorker();const {data:current,error:readError}=await supabase.from("prayer_requests").select("is_public,status").eq("id",prayerId).single();if(readError||!current)throw new Error("Petición no disponible.");const {error}=await supabase.from("prayer_requests").update({status,answered_at:status==="answered"?new Date().toISOString():null}).eq("id",prayerId);if(error)throw new Error("No tienes permiso para moderar oración.");if(status==="approved"&&current.is_public&&current.status!=="approved")await notifyPublishedPrayer(prayerId);refresh();}
