"use client";

import { useActionState } from "react";
import { Button } from "@/components/ui/button";
import { Field, Input, Select, Textarea } from "@/components/ui/input";
import { isoToLocalInput } from "@/lib/events/calendar";
import { createEvent, updateEvent, type EventFormState } from "./actions";

type Option={ id:string; name:string; colorHex?:string };
type Initial={ id:string; name:string; description:string|null; startsAt:string; endsAt:string|null; location:string|null; mapUrl:string|null; imageUrl:string|null; categoryId:string|null; ministryId:string|null; attendanceMode:string; capacity:number|null; registrationDeadline:string|null; status:string; isFeatured:boolean; notifyOnPublish:boolean; recurrenceKind:string };

export function EventForm({ categories, ministries, initial }: { categories:Option[]; ministries:Option[]; initial?:Initial }) {
  const handler=initial ? updateEvent : createEvent;
  const [state,action,pending]=useActionState<EventFormState,FormData>(handler,{});
  return (
    <form action={action} className="space-y-4 rounded-[var(--radius-card)] border border-manta bg-white p-5 dark:bg-manta">
      {initial ? <input type="hidden" name="id" value={initial.id} /> : null}
      <Field label="Nombre de la actividad" htmlFor="name"><Input id="name" name="name" required minLength={3} defaultValue={initial?.name ?? ""} placeholder="Servicio Dominical" /></Field>
      <Field label="Descripción" htmlFor="description"><Textarea id="description" name="description" defaultValue={initial?.description ?? ""} placeholder="Información útil para quienes asistirán" /></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Inicio" htmlFor="startsAt"><Input id="startsAt" name="startsAt" type="datetime-local" required defaultValue={isoToLocalInput(initial?.startsAt)} /></Field><Field label="Finaliza (opcional)" htmlFor="endsAt"><Input id="endsAt" name="endsAt" type="datetime-local" defaultValue={isoToLocalInput(initial?.endsAt)} /></Field></div>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Categoría" htmlFor="categoryId"><Select id="categoryId" name="categoryId" required defaultValue={initial?.categoryId ?? categories[0]?.id}>{categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></Field><Field label="Ministerio responsable (opcional)" htmlFor="ministryId"><Select id="ministryId" name="ministryId" defaultValue={initial?.ministryId ?? ""}><option value="">General</option>{ministries.map((m)=><option key={m.id} value={m.id}>{m.name}</option>)}</Select></Field></div>
      <Field label="Ubicación" htmlFor="location"><Input id="location" name="location" defaultValue={initial?.location ?? ""} placeholder="Templo, parque, hospital, casa…" /></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Enlace de mapa" htmlFor="mapUrl"><Input id="mapUrl" name="mapUrl" type="url" defaultValue={initial?.mapUrl ?? ""} placeholder="https://maps.google.com/..." /></Field><Field label="Imagen de portada" htmlFor="imageUrl"><Input id="imageUrl" name="imageUrl" type="url" defaultValue={initial?.imageUrl ?? ""} placeholder="https://..." /></Field></div>
      <div className="grid gap-4 sm:grid-cols-3"><Field label="Asistencia" htmlFor="attendanceMode"><Select id="attendanceMode" name="attendanceMode" defaultValue={initial?.attendanceMode ?? "none"}><option value="none">Sin confirmación</option><option value="rsvp">Botón “Asistiré”</option><option value="registration">Inscripción</option></Select></Field><Field label="Cupo (opcional)" htmlFor="capacity"><Input id="capacity" name="capacity" type="number" min="1" defaultValue={initial?.capacity ?? ""} /></Field><Field label="Cierre de inscripción" htmlFor="registrationDeadline"><Input id="registrationDeadline" name="registrationDeadline" type="datetime-local" defaultValue={isoToLocalInput(initial?.registrationDeadline)} /></Field></div>
      {!initial ? <fieldset className="space-y-3 rounded-2xl border border-manta p-4"><legend className="px-2 text-sm font-semibold">Repetición</legend><div className="grid gap-4 sm:grid-cols-2"><Field label="Frecuencia" htmlFor="recurrenceKind"><Select id="recurrenceKind" name="recurrenceKind" defaultValue="single"><option value="single">Una sola vez</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option></Select></Field><Field label="Repetir hasta" htmlFor="recurrenceUntil"><Input id="recurrenceUntil" name="recurrenceUntil" type="date" /></Field></div><div><p className="mb-2 text-sm font-medium">Días de la semana (para semanal)</p><div className="flex flex-wrap gap-3 text-sm">{[[1,"Lun"],[2,"Mar"],[3,"Mié"],[4,"Jue"],[5,"Vie"],[6,"Sáb"],[0,"Dom"]].map(([value,label])=><label key={value} className="flex items-center gap-1"><input type="checkbox" name="weekdays" value={value} />{label}</label>)}</div></div><p className="text-xs text-tinta-suave">Si no marcas días, se repetirá el mismo día de la semana del primer evento. Las series se generan hasta 18 meses.</p></fieldset> : <p className="rounded-xl bg-anil-50 p-3 text-xs text-anil-800">Estás editando una ocurrencia. La serie puede cancelarse desde la lista de eventos sin alterar actividades pasadas.</p>}
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Estado" htmlFor="status"><Select id="status" name="status" defaultValue={initial?.status === "draft" ? "draft" : "published"}><option value="published">Publicado</option><option value="draft">Borrador</option></Select></Field><div className="space-y-2 pt-1"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="isFeatured" defaultChecked={initial?.isFeatured ?? false} /> Destacar actividad</label><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" name="notify" defaultChecked={initial?.notifyOnPublish ?? true} /> Notificar al publicar</label></div></div>
      {state.error ? <p role="alert" className="text-sm text-error">{state.error}</p> : null}{state.ok ? <p role="status" className="text-sm font-semibold text-balsamo-700">{state.count && state.count>1 ? `Serie creada con ${state.count} actividades.` : "Actividad guardada correctamente."}</p> : null}
      <Button type="submit" disabled={pending} className="w-full">{pending ? "Guardando…" : initial ? "Guardar cambios" : "Crear actividad"}</Button>
    </form>
  );
}
